version: '3.1'

services:

#postgres :
  postgre_db:
    image: postgres:15
    container_name: postgre_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: CHAT
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - myapp_network

networks:
  myapp_network:
